### ISSUE TITLE
Testy pojedynczej relacji Modifies z with

### ISSUE THREAD

**Issue by Hatulak** [exomatexo/aitsi#164]

**Comment by speednow** [comment]
![image](https://user-images.githubusercontent.com/38276663/82144372-26d7d380-9847-11ea-9d93-01fb481200a6.png)
![image](https://user-images.githubusercontent.com/38276663/82144474-466efc00-9847-11ea-8846-9789770364da.png)
![image](https://user-images.githubusercontent.com/38276663/82144602-6d2d3280-9847-11ea-9af7-795bfc8997a0.png)
![image](https://user-images.githubusercontent.com/38276663/82144689-8c2bc480-9847-11ea-8ba9-c11b0d8284e6.png)
plik testów modifies_w.txt
