### ISSUE TITLE
Bugi w relacji Calls

### ISSUE THREAD

**Issue by exomatt** [exomatexo/aitsi#213]
kod source_simple_1.txt
testy calls.txt

zapytanie: 
procedure p,q;
Select p such that Calls (p, q) with p.procName = "Init"
oczekiwano:
none
otrzymano:
 Init

zapytanie: 
procedure p,q;
Select p such that Calls (p, q) with q.procName = "Second"
oczekiwano:
ABC
otrzymano:
 none

zapytanie: 
procedure p,q;
Select p such that Calls (p, q) with q.procName = "Init"
oczekiwano:
ABC, Second
otrzymano:
 none

**Comment by Hatulak** [comment]
Lecą błędy w query processorze
